config/routes.rb
Semanticdoc::Application.routes.draw do
  root :to => "home#index"
  resources :semantic_schemas
  namespace :admin do
    resources :semantic_schemas
    get "/" => "home#index", as: :panel
  end
end

app/models/basic_data_type.rb
class BasicDataType < ActiveRecord::Base
  # Mass Assignment
  attr_accessible :name
  
  # Relations
  include ::Sdoc::DataModel
end

app/models/data_model.rb
class DataModel < ActiveRecord::Base
  # Mass Assignment
  attr_accessible :acceptable_data, :data_id
  
  # Relations
  has_many :properties, inverse_of: :data_model
  belongs_to :acceptable_data, polymorphic: true
  
  # Methods
  def name
    @name ||= self.acceptable_data.name
  end
end

app/models/property.rb
class Property < ActiveRecord::Base
  # Mass Assignment
  attr_accessible :semantic_schema_id, :data_model_id, :name, :description, :sample_data
  
  # Relations
  belongs_to :semantic_schema, inverse_of: :properties
  belongs_to :data_model, inverse_of: :properties
end

app/models/semantic_schema.rb
class SemanticSchema < ActiveRecord::Base
  # Mass Assignment
  attr_accessible :name, :description, :ancestry, :properties_attributes, :parent_id
  
  # Relations
  has_ancestry
  has_many :properties, inverse_of: :semantic_schema
  include Sdoc::DataModel
  
  # Nested attributes
  accepts_nested_attributes_for :properties, reject_if: lambda { |p| p[:data_model_id].blank? || p[:name].blank? }, allow_destroy: true
  
end

app/controllers/admin/application_controller.rb
class Admin::ApplicationController < ActionController::Base
  protect_from_forgery
  layout "admin_panel"
  before_filter :authenticate
  def authenticate
    authenticate_or_request_with_http_basic do |username, password|
      username == AppConfig["username"] && password == AppConfig["password"]
    end
  end
end

app/controllers/admin/home_controller.rb
class Admin::HomeController < Admin::ApplicationController
  def index
    
  end
end

app/controllers/admin/semantic_schemas_controller.rb
class Admin::SemanticSchemasController < Admin::ApplicationController
  respond_to :html
  def new
    @semantic_schema = SemanticSchema.new
    
    3.times do
      @semantic_schema.properties.build
    end
  end
  
  def create
    @semantic_schema = SemanticSchema.new(params[:semantic_schema])
    if @semantic_schema.save
      redirect_to admin_semantic_schema_path(@semantic_schema), :notice => "Successfully created semantic schema."
    else
      render :action => 'new'
    end
  end
  
  def edit
    @semantic_schema = SemanticSchema.find(params[:id])
  end
  
  def update
    @semantic_schema = SemanticSchema.find(params[:id])
    if @semantic_schema.update_attributes(params[:semantic_schema])
      redirect_to admin_semantic_schema_path(@semantic_schema), :notice  => "Successfully updated semantic schema."
    else
      render :action => 'edit'
    end
  end
  
  def show
    @semantic_schema = SemanticSchema.find(params[:id])
  end
  
  def index
    @semantic_schemas = SemanticSchema.roots
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/semantic_schemas_controller.rb
class SemanticSchemasController < ApplicationController
  def show
    @semantic_schema = SemanticSchema.find(params[:id])
  end

  def index
    @semantic_schemas = SemanticSchema.roots
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/semantic_schemas/_form.html.erb
<%= nested_form_for [:admin, @semantic_schema] do |f| %>
  <div class="row">
  <%= f.label :parent_id, "Parent Semantic Schema", class: "span3" %>
  <%= f.select(:parent_id, options_for_select(SemanticSchema.order("name ASC").all.collect {|ss| [ss.name, ss.id]}, f.object.parent_id), { :include_blank => true }, class: "span3") %>
  </div>
  <hr />
  <div class="row">
    <%= f.label :name, "*Name", class: "span3" %>
    <%= f.text_field :name, :class => "span3" %>
  </div>
  <hr />
  <div class="row">
    <%= f.label :description, "Description", class: "span3" %>
    <%= f.text_field :description, :class => "span6" %>
  </div>
  <hr />  <div class="inner-fields">
    <%= f.fields_for :properties do |builder| %>
      <% render :partial => 'property_fields', :locals => {:f => builder} %>
    <% end %>
    <%= f.link_to_add "<i class='icon-plus'></i> add a property".html_safe, :properties, :class => "btn btn-success" %>
  </div>
  <hr />
  <%= f.submit "save", class: "btn btn-primary" %>
<% end %>

app/views/admin/semantic_schemas/_property_fields.html.erb
<div class="field clear">
  <div class="row">
    <label class="pull-right"><%= f.link_to_remove "<i class='icon-remove'></i> remove".html_safe, class: "btn" %></label>
  <%= f.label :data_model_id, "*Data Type", class: "span3" %>
  <%= f.select(:data_model_id, options_for_select(DataModel.all.sort! { |a,b| a.name.downcase <=> b.name.downcase }.collect {|dm| [dm.acceptable_data.name, dm.id]}, f.object.data_model_id), {}, :class => "span3") %>
  </div>
  <div class="row">
    <%= f.label :name, "*Name", class: "span3" %><%= f.text_field :name, class: "span5" %>
  </div>
  <div class="row">
    <%= f.label :description, "*Description", class: "span3" %><%= f.text_field :description, class: "span8" %>
  </div>
  <div class="row">
    <%= f.label :sample_data, "Sample data", class: "span3" %><%= f.text_field :sample_data, class: "span8" %>
  </div>
</div>
<hr />

app/views/admin/semantic_schemas/_semantic_schema.html.erb
<li>
  <%=link_to semantic_schema.name, admin_semantic_schema_path(semantic_schema)%>: <%=semantic_schema.properties.order("name ASC").map {|p| p.name}.join(", ")%>
  <% if semantic_schema.has_children? %>
  <ul>
    <% semantic_schema.children.order("name ASC").each do |sc| %>
      <%= render "semantic_schema", semantic_schema: sc %>
    <% end%>
  </ul>
  <% end %>
</li>

app/views/admin/semantic_schemas/edit.html.erb
<h1>Edit Semantic Schema</h1>
<p>Edit the current semantic schema!</p>
<hr />

<%= render 'form'%>

app/views/admin/semantic_schemas/index.html.erb
<h1>Full Hierarchy</h1>
<hr />
<ul>
<% @semantic_schemas.each do |semantic_schema| %>
  <%= render "semantic_schema", semantic_schema: semantic_schema %>
<% end %>
</ul>

app/views/admin/semantic_schemas/new.html.erb
<h1>New Semantic Schema</h1>
<p>Create a new semantic schema!</p>
<hr />

<%= render 'form'%>

app/views/admin/semantic_schemas/show.html.erb
<ul class="breadcrumb">
<% @semantic_schema.path.each do |schema| %>
  <% unless schema.id == @semantic_schema.id %>
  <li><%= link_to schema.name, admin_semantic_schema_path(schema) %> <span class="divider">></span></li>
  <% end %>
<% end %>
  <li><%= link_to @semantic_schema.name, admin_semantic_schema_path(@semantic_schema) %></li>
  <li class="description"><div><%=@semantic_schema.description%></div></li>
</ul>
<table class="table table-bordered table-condensed table-striped">
  <thead>
    <tr>
      <th class="span2">Property</th>
      <th class="span3">Expected Type</th>
      <th class="span6">Description</th>
    </tr>
  </thead>
  <tbody>
<% @semantic_schema.path.each do |schema| %>
    <tr>
      <th colspan="3" class="span12">Properties from <%=link_to schema.name, admin_semantic_schema_path(schema)%> <%= link_to "<i class='icon-edit'></i>".html_safe, edit_admin_semantic_schema_path(schema) %></th>
    </tr>
    <% schema.properties.order("name ASC").each do |property| %>
    <tr>
      <th class="span2"><%=property.name %></th>
      <td class="span3"><%=property.data_model.name%></td>
      <td class="span7"><%=property.description%><div><strong>Example:</strong> <%=property.sample_data%></div></td>
    </tr>
    <% end %>
<% end %>
  </tbody>
</table>

app/views/home/index.html.erb
<% content_for :meta do %>
  <title>Semantic Web Work in Turkey, Event Ontologies, dakick.com - semanticdoc</title>
  <meta name="description" content="Detailed Information about Event Ontologies (still in progress) by Turkey's leading company, dakick.com.">
<% end %>
<div class="hero-unit">
  <h1>Semantic Web Work!<image src="<%=image_path('semantic.png')%>" class="pull-right"></h1>
  <p style="margin:30px 0px 30px 0px; text-align: justify; ">Event, Creative Work (movie, exhibition, trade show, sports game, conference, performing arts, tv program, concert), People, Place Ontologies for dakick.com.</p>
  <p><a class="btn btn-primary btn-large" href="/semantic_schemas">Start exploring it!</a></p>
</div>

app/views/layouts/admin_panel.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "SemanticDoc/Admin" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "SemanticDoc/Admin", admin_panel_path, class: "brand"%>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Full Hierarchy", admin_semantic_schemas_path  %></li>
              <li><%= link_to "New Schema", new_admin_semantic_schema_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; <%=AppConfig["copyright"]%> 2012</p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= yield(:meta) %>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "SemanticDoc", "/", class: "brand"%>
          <div class="container nav-collapse">
            <ul class="nav">
              <li><%= link_to "Full Hierarchy", semantic_schemas_path  %></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
      <div class="content">
        <div class="row">
           <div class="span12">
              <%= yield %>
            </div>
        </div><!--/row-->
      </div><!--/content-->

      <footer>
        <p>&copy; <%=AppConfig["copyright"]%> 2012 <span class="pull-right">powered by <a href="http://github.com/dakick/semanticdoc">semanticdoc</a></span></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>
    <script type="text/javascript">

      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-16133327-2']);
      _gaq.push(['_setDomainName', '.dakick.com']);
      _gaq.push(['_trackPageview']);
      setTimeout('_gaq.push([\'_trackEvent\', \'NoBounce\', \'Over 30 seconds\'])',30000);

      (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();

    </script>
  </body>
</html>

app/views/semantic_schemas/_semantic_schema.html.erb
<li>
  <%=link_to semantic_schema.name, semantic_schema_path(semantic_schema)%>: <%=semantic_schema.properties.order("name ASC").map {|p| p.name}.join(", ")%>
  <% if semantic_schema.has_children? %>
  <ul>
    <% semantic_schema.children.order("name ASC").each do |sc| %>
      <%= render "semantic_schema", semantic_schema: sc %>
    <% end%>
  </ul>
  <% end %>
</li>

app/views/semantic_schemas/index.html.erb
<% content_for :meta do %>
  <title>Full Hierarchy - semanticdoc</title>
<% end %>
<h1>Full Hierarchy</h1>
<hr />
<ul>
<% @semantic_schemas.each do |semantic_schema| %>
  <%= render "semantic_schema", semantic_schema: semantic_schema %>
<% end %>
</ul>

app/views/semantic_schemas/show.html.erb
<% content_for :meta do %>
  <title><%= @semantic_schema.name %> Ontology - semanticdoc</title>
<% end %>
<ul class="breadcrumb">
<% @semantic_schema.path.each do |schema| %>
  <% unless schema.id == @semantic_schema.id %>
  <li><%= link_to schema.name, semantic_schema_path(schema) %> <span class="divider">></span></li>
  <% end %>
<% end %>
  <li><%= link_to @semantic_schema.name, semantic_schema_path(@semantic_schema) %></li>
  <li class="description"><div><%=@semantic_schema.description%></div></li>
</ul>
<table class="table table-bordered table-condensed table-striped">
  <thead>
    <tr>
      <th class="span2">Property</th>
      <th class="span3">Expected Type</th>
      <th class="span6">Description</th>
    </tr>
  </thead>
  <tbody>
<% @semantic_schema.path.each do |schema| %>
    <tr>
      <th colspan="3" class="span12">Properties from <%=link_to schema.name, semantic_schema_path(schema)%></th>
    </tr>
    <% schema.properties.order("name ASC").each do |property| %>
    <tr>
      <th class="span2"><%=property.name %></th>
      <td class="span3"><%=property.data_model.name%></td>
      <td class="span7"><%=property.description%><%="(<strong>Example:</strong> #{property.sample_data})".html_safe if property.sample_data.present? %></div></td>
    </tr>
    <% end %>
<% end %>
  </tbody>
</table>